grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2

model_selection:

  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false

  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 6

  module_2:
    class: DecisionTreeRegressor
    module: sklearn.tree
    params:
      criterion:
      - squared_error
      max_features:
      - None
    search_param_grid:
      criterion:
      - squared_error
      - friedman_mse
      - absolute_error
      - poisson
      max_features:
      - 'auto'
      - 'sqrt'
      - 'log2'

  module_3:
    class: GradientBoostingRegressor
    module: sklearn.ensemble
    params:
      learning_rate: 0.01
      n_estimators: 100
      subsample: 0.5
    search_param_grid:
      learning_rate:
      - 0.01
      - 0.1
      n_estimators:
      - 50
      - 100
      - 500
      subsample:
      - 0.5
      - 0.7
      max_depth:
      - 3
      - 9







